version: "3.1"
services:

  shiny-2:
    image: kuzmenkov/shinyserv
    ports:
      - "3838"
    volumes:
      - "/srv/test:/srv/shiny-server"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  proxy-server:
    image: kuzmenkov/reverseproxy
    ports:
      - "80:80"
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]